apiVersion: batch/v1
kind: Job
metadata:
  name: walklog-setup-web
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: walklog-setup-web
        image: chezsugi/walklog_web 
        command:
        - /var/www/setup.sh
        volumeMounts:
        - mountPath: /var/www/public
          name: walklog-public
        envFrom:
        - secretRef:
            name: walklog-env
      restartPolicy: OnFailure
      volumes:
      - name: walklog-public
        hostPath:
          path: /var/k8s/volumes/walklog-public
          type: DirectoryOrCreate